USE DonShalo;
GO
IF EXISTS (SELECT * FROM sys.procedures WHERE name = 'usp_VerPersonal') 
	BEGIN
		DROP PROCEDURE usp_VerPersonal;
	END
GO

CREATE PROCEDURE usp_VerPersonal
(
	@pId INT
)
AS
BEGIN
	SELECT 
		PER.Id AS [ID],
		PER.TipoDocumento AS [TIPO_DOCUMENTO],
		PER.NumeroDocumento AS [NUMERO_DOCUMENTO],
		PER.Nombre AS [NOMBRE],
		PER.ApellidoPaterno AS [APELLIDO_PATERNO],
		PER.ApellidoMaterno AS [APELLIDO_MATERNO],
		PER.Telefono AS [TELEFONO],
		PER.Correo AS [CORREO],
		(CASE PER.Estado
			WHEN 'A' THEN 'ACTIVO'
			WHEN 'I' THEN 'INACTIVO' END) AS [ESTADO],
		ROL.Id AS [ROL],
		SUC.Id AS [SUCURSAL]
	FROM PERSONAL PER
	LEFT JOIN ROL ROL ON ROL.Id = PER.IdRol
	LEFT JOIN ASIGNACIONPERSONAL ASI ON ASI.IdPersonal = PER.Id
	LEFT JOIN SUCURSAL SUC ON SUC.Id = ASI.IdSucursal
	WHERE 
		PER.Id LIKE @pId OR 
		(@pId IS NULL OR @pId = '')

END